### ISSUE TITLE
Failure pulling user-data from CDROM

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#2]
Latest builds from CI fails tests cause of this:

```
INFO[0000] Processing stage step 'Pull data from provider (local)'  commands=0 delete_entities=0 entities=0 files=0 nameserver=0 step="Pull data from provider (local)"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/diskfs/go-diskfs/filesystem/iso9660.parseDirEntry({0x10ab068, 0x10ab068, 0xa}, 0xc000206038)
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660/directoryentry.go:281 +0x56f
github.com/diskfs/go-diskfs/filesystem/iso9660.Read({0xc3f900, 0xc00000f138}, 0x5b000, 0x0, 0xc0002062d8)
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660/iso9660.go:223 +0x9fa
github.com/diskfs/go-diskfs/disk.(*Disk).GetFilesystem(0xc00007d5e0, 0x0)
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/diskfs/go-diskfs/disk/disk.go:227 +0x238
github.com/davidcassany/linuxkit/pkg/metadata/providers.FindCIs()
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/davidcassany/linuxkit/pkg/metadata/providers/provider_cdrom.go:85 +0x3a6
github.com/davidcassany/linuxkit/pkg/metadata/providers.ListCDROMs()
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/davidcassany/linuxkit/pkg/metadata/providers/provider_cdrom.go:45 +0xae
github.com/mudler/yip/pkg/plugins.DataSources({{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...)
        /luetbuild/go/src/github.com/mudler/yip/pkg/plugins/datasource.go:49 +0xb4b
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).Apply(0xc00023f400, {0x7fff88984ac2, 0x7}, {{0xc0002a2ec0, 0x1}, 0xc00024f4a0}, {0xc56f28, 0x10aad40}, {0xc3fc90, 0x10ab068})
        /luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:162 +0xcd9
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).run(0x20, {0x7fff88984ac2, 0x7}, {0xc0002a2de0, 0x1e}, {0xc56f28, 0x10aad40}, {0xc3fc90, 0x10ab068}, 0xb80300, ...)
        /luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:92 +0x13a
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).walkDir.func1({0xc0002a2de0, 0x0}, {0xc49240, 0xc0002a6340}, {0x0, 0x0})
        /luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:72 +0x20b
github.com/twpayne/go-vfs.walk({0x7fe455ad6818, 0x10aad40}, {0xc0002a2de0, 0x1e}, 0xc000207bb0, {0xc49240, 0xc0002a6340}, {0x0, 0x0})
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/twpayne/go-vfs/walk.go:30 +0xbb
github.com/twpayne/go-vfs.walk({0x7fe455ad6818, 0x10aad40}, {0x7fff88984aca, 0xb}, 0xc000207bb0, {0xc49240, 0xc000271ba0}, {0x0, 0x0})
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/twpayne/go-vfs/walk.go:47 +0x2e5
github.com/twpayne/go-vfs.Walk({0x7fe455ad6818, 0x10aad40}, {0x7fff88984aca, 0xb}, 0x7fff88984aca)
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/twpayne/go-vfs/walk.go:58 +0x66
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).walkDir(0x10aad40, {0x7fff88984ac2, 0x7fe455ac3370}, {0x7fff88984aca, 0xb}, {0xc56f28, 0x10aad40}, {0xc3fc90, 0x10ab068})
        /luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:55 +0x10e
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).runStage(0xc00023f400, {0x7fff88984ac2, 0x7}, {0x7fff88984aca, 0xb}, {0xc56f28, 0x10aad40}, {0xc3fc90, 0x10ab068})
        /luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:104 +0x21c
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).Run(0xe, {0x7fff88984ac2, 0x7}, {0xc56f28, 0x10aad40}, {0xc3fc90, 0x10ab068}, {0xc00024ec60, 0x1, 0x3})
        /luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:122 +0x147
github.com/mudler/yip/cmd.glob..func1(0x10709a0, {0xc00024ec60, 0x1, 0x3})
        /luetbuild/go/src/github.com/mudler/yip/cmd/root.go:107 +0x2a8
github.com/spf13/cobra.(*Command).execute(0x10709a0, {0xc000030090, 0x3, 0x3})
        /luetbuild/go/src/github.com/mudler/yip/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
```

See also: https://github.com/diskfs/go-diskfs/issues/103

**Comment by mudler** [comment]
https://github.com/davidcassany/linuxkit/pull/3
https://github.com/davidcassany/linuxkit/pull/4

**Comment by mudler** [comment]
Needs an updated version of yip with a bump of go-diskfs

**Comment by mudler** [comment]
A new yip version has been tagged with the submodules bump (go-diskfs, linuxkit with the above patches): https://github.com/mudler/yip/compare/0.10.0...0.10.1

**Comment by mudler** [comment]
Current workaround for CI is to drop the -rock flag: https://github.com/rancher-sandbox/os2/commit/8daf1ef6ce6d5a9b984e530ea388bcc6373b2ac5

**Comment by mudler** [comment]
Blocked by https://github.com/rancher-sandbox/cOS-toolkit/issues/1104
